### PR TITLE
Assigning to my_string variable

### PR DESCRIPTION
**Pull request by vivek28111992**
To print the expected output `my_string` variable needs to be assigned value of replaced substring.

### CODE REVIEW

**Comment by jerry-git** [comment]
Thanks for the contribution! 👍

**Comment by jerry-git** [comment]
After having a closer look, my original idea seems to have been to highlight that `replace` is not done in-place. I made the intention more explicit in https://github.com/jerry-git/learn-python3/commit/4a4dec431f711a5f0e0fd4c436051c932d6227c1.

**Comment by vivek28111992** [comment]
@jerry-git Is there plan for creating exercises and material on back log?

**Review by Balagans — COMMENTED** [review]
Ооу

**Pull request merged**
